export const registry = {
  placeholder: () => import('../apps/placeholder/index.js'),
  defrag: () => import('../apps/defrag/index.js'),
  terminal: () => import('../apps/terminal/index.js'),
  editor: () => import('../apps/editor/index.js'),
  viewer: () => import('../apps/viewer/index.js'),
  folder: () => import('../apps/folder/index.js'),
  account: () => import('../apps/account/index.js'),
  aftere: () => import('../apps/aftere/index.js'),
  garden: () => import('../apps/garden/index.js'),
  shop: () => import('../apps/shop/index.js'),
  cmos: () => import('../apps/cmos/index.js'),
  goddoodle: () => import('../apps/goddoodle/index.js'),
  tasks: () => import('../apps/tasks/index.js'),
  hifi: () => import('../apps/hifi/index.js'),
  sweeper: () => import('../apps/sweeper/index.js'),
  solitaire: () => import('../apps/solitaire/index.js'),
  crayon: () => import('../apps/crayon/index.js'),
  drawings: () => import('../apps/drawings/index.js'),
  elephant: () => import('../apps/elephant/index.js'),
  magen: () => import('../apps/magen/index.js'),
  cook: () => import('../apps/cook/index.js'),
  display: () => import('../apps/display/index.js'),
  about: () => import('../apps/about/index.js'),

  bekkedal: () => import('../apps/bekkedal/index.js'),
  bottle: () => import('../apps/bottle/index.js'),
  notes: () => import('../apps/notes/index.js'),
  neofetch: () => import('../apps/neofetch/index.js'),


};
